[package]
name = "boatbomber/glassmorphicui"
description = "Glassmorphic UI in Roblox"
version = "1.0.0"
license = "MPL 2.0"
authors = ["boatbomber (https://boatbomber.com)"]
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json"]
exclude = ["**"]

[dependencies]
EditableImageBlur = "boatbomber/editableimageblur@1.0.0"
PixelColorApproximation = "boatbomber/pixelcolorapproximation@0.4.0"

[dev-dependencies]
Jest = "jsdotlua/jest@3.10.0"
JestGlobals = "jsdotlua/jest-globals@3.10.0"
